### ISSUE TITLE
Anonymous users see admin tabs/links

### ISSUE THREAD

**Issue by Algernon3000** [vlegoff/evennia-wiki#1]
When viewing wiki as anonymous (without being logged in), user can still see Edit, Settings & History tabs/links.

**Comment by vincent-lg** [comment]
This has been fixed and will be available shortly, in evennia-wiki 0.4.  The history tab has been linked to the ability to view the page (not write it), so anonymous users will still be able to see this tab (which is completely empty right now).  If that's not a desired behavior, we might try to find some compromise on this.

Additionally, when clicking on "child pages", the list of pages to view is displayed no matter what.  However, the ability to create a new page is not displayed if the user has no "write" privilege on the parent page.  This, too, might need further debating.

Thanks for reporting!  Letting this issue open until tests have been completed, so don't hesitate to close it.
