### ISSUE TITLE
"/wiki" on a default installation results in a 404

### ISSUE THREAD

**Issue by friarzen** [vlegoff/evennia-wiki#2]
This is because there is no root page.

Workaround is to log into Evennia's admin pages and then go to /wiki to create the new content.

The suggested solution is to build a "default" root page as part of installation.

**Comment by vincent-lg** [comment]
This has been fixed and will be available on evennia-wiki 0.5.  The workaround is to create the root page each time you ask for a wiki page (if the root page doesn't exist).  The following default content is written in the root page:

**Welcome** to your new root page on [evennia-wiki](https://github.com/vincent-lg/evennia-wiki), a simple wiki to be integrated into [Evennia games](www.evennia.com).

What to do now?  You could start by editing this page to remove this default content.  You will need to log into an account with enough privileges (your superuser is a good choice).

- What syntax to use?  Check evennia-wiki's [syntax](https://vincent-lg.github.io/evennia-wiki/syntax.html).
- How to add new pages?  Check the evennia-wiki's [documentation on writing in the wiki](https://vincent-lg.github.io/evennia-wiki/page.html).
- How is this wiki structured?  Check out evennia-wiki's [structure](https://vincent-lg.github.io/evennia-wiki/structure.html).
- How to read and write wiki pages from my Evennia code?  Check out evennia-wiki's [simple API](https://vincent-lg.github.io/evennia-wiki/api.html).
- Have another question?  Check out evennia-wiki's [documentation](https://vincent-lg.github.io/evennia-wiki).

> If you would like to contribute to this project, either by just suggesting features or contribute to its source code, feel free to drop by [evennia-wiki's Github page](https://github.com/vincent-lg/evennia-wiki).

**Enjoy!**

Thanks for reporting!
